spring:
    profiles: 
        active: dev

server:
    port: 8021

logging:
    level:
        root: INFO
    
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        lazyLoadingEnabled: true
        aggressiveLazyLoading: false
        mapUnderscoreToCamelCase: true

---

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://localhost:3306/ssucodedb?useUnicode=true&characterEncoding=utf8&connectTimeout=300000&socketTimeout=300000&allowMultiQueries=true

        username: ssucode
        password: ssucode12!

---

spring:
    config:
        activate:
            on-profile: real
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/ssucodedb?useUnicode=true&characterEncoding=utf8&connectTimeout=300000&socketTimeout=300000&allowMultiQueries=true

        username: ssucode
        password: ssucode12!